spring:
  config:
    import: aws-parameterstore:/profile-mission/prod/INFOMATION/

  datasource:
    url: ${url}
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      region:
        static: ap-northeast-2


management:
  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true


logging:
  level:
    root: ERROR