spring:
  datasource:
    url: jdbc:mysql://assign-secure0804.cvags4620l8k.ap-northeast-2.rds.amazonaws.com:3306/test
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
    import: aws-parameterstore:/camp-health-app/prod/


management:
  endpoint:
    health:
      show-details: never

  info:
    env:
      enabled: true


info:
  app:
    message: ${APP_MESSAGE}


logging:
  level:
    root: ERROR