spring:
  config:
    import: aws-parameterstore:/profile-mission/prod/INFOMATION/

  datasource:
    url: ${url}
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: project-info-yeang976-files


management:
  endpoint:
    web:
      exposure:
        include: info, health

  info:
    env:
      enabled: true

info:
  database:
    information: ${INFOMATION}

logging:
  level:
    root: ERROR